test: test_1 test_2
	@echo '--- test/Makefile $@'

test_1:
	./$(package) test_1.txt
	@echo '--- test/Makefile $@'

test_2:
	./$(package) test_2.txt
	@echo '--- test/Makefile $@'


.PHONY: test test_1
